version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 54322:5432
    environment:
      POSTGRESQL_DATABASE: test
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password